name: QRCallWatchDemo
options:
  bundleIdPrefix: com.stable.qrcallbox
  deploymentTarget:
    watchOS: "9.0"
  developmentLanguage: en

targets:
  QRCallWatchDemo:
    type: application.watchapp2
    platform: watchOS
    deploymentTarget: "9.0"
    sources:
      - path: Sources
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDevelopmentRegion: $(DEVELOPMENT_LANGUAGE)
        CFBundleDisplayName: QRCall
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKAGE_TYPE)
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        WKWatchKitApp: true
        WKApplication: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.stable.qrcallbox.watchdemo
        DEVELOPMENT_TEAM: ""
        ENABLE_PREVIEWS: YES
        SWIFT_VERSION: "5.0"
        WATCHOS_DEPLOYMENT_TARGET: "9.0"
        SDKROOT: watchos
        TARGETED_DEVICE_FAMILY: "4"
        SKIP_INSTALL: NO
